### ISSUE TITLE
Suggestion to add geofileops

### ISSUE THREAD

**Issue by theroggy** [opengeos/geospatial#76]
Would be nice if [geofileops](https://github.com/geofileops/geofileops) could be added...

**Comment by giswqs** [comment]
Can you bump the upper bound of the gdal dependency? `"gdal>=3.6,<3.10"` is too restrictive, which fails all GitHub Action. Recommend updating it to `"gdal>=3.6,<3.12"`

https://github.com/opengeos/geospatial/actions/runs/11593197315/job/32276716787

**Comment by theroggy** [comment]
gdal 3.10 is probably only a few days away, but at this time the latest version of gdal is still 3.9.3 ([gdal on pypi](https://pypi.org/project/GDAL), [gdal on github](https://github.com/OSGeo/gdal/releases)), so that's not going to help.

gdal is indeed not trivial to install using pip. I though the geospatial package targetted conda-forge installation?

**Comment by giswqs** [comment]
I use `pip install --find-links https://girder.github.io/large_image_wheels gdal` in the GitHub Actions for testing Ubuntu Linux. It was able to install GDAL 3.10, but GDAL 3.9 failed. Not sure why. https://github.com/opengeos/geospatial/pull/77

Anyway, I have added geofileops to the conda-forge package. 
https://github.com/conda-forge/geospatial-feedstock/pull/49

I won't be able to add it as a pip dependency due to the GDAL dependency.
